package homework.java.khaled.exceptions_handling;
import java.io.*;
import java.io.IOException;
public class ExcepTest_01 {
    public static void main(String args[]) {
        /*try {
            int a[] = new int[2];
            System.out.println("Access element three :" + a[3]);
        }catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("Exception thrown  :" + e);
        }
        System.out.println("Out of the block");*/

        /*try {
            // Protected code
        }catch(ExceptionType1 e1) {
            // Catch block
        }catch(ExceptionType2 e2) {
            // Catch block
        }catch(ExceptionType3 e3) {
            // Catch block
        }*/


        /*try {
            file = new FileInputStream(fileName);
            x = (byte) file.read();
        } catch (IOException i) {
            i.printStackTrace();
            return -1;
        } catch (FileNotFoundException f) // Not valid!
        {
        f.printStackTrace();
        return -1;
        }*/



    }
}
